### PR TITLE
Update alias_PICO-8.txt with 12,000 titles

### PR DESCRIPTION
**Pull request by neilswann80**
found an archive.org download with 12k unique game cart names.  Wrote a script to pull all the alias names from lexaloffle.com 

Fixed any friendly names that begin with a `(` to prevent SimpleMenu crash
also removed any blank alias names.  

There are duplicate aliases as different versions of the same game have unique cart names, left them in for completeness.

### CODE REVIEW

**Comment by eduardofilo** [comment]
Have you been able to check if it slows down SimpleMenu by having to check such a large file?

**Comment by neilswann80** [comment]
> Have you been able to check if it slows down SimpleMenu by having to check such a large file?

Yes, no slow down at all.  I also wondered if there would be.

I have around 300 PICO-8 games that all require alias names and they were al puled from txt file in this PR.

The only time SimpleMenu slows for me is on the SCUMVM and AMIGA sections, but that's always been the case!  :)

**Comment by eduardofilo** [comment]
> There is no slow down at all! I also wondered if there would be.

OK. So we go ahead with the PR.

> Do you think it's worth also adding extension `.p8.png` to the SimpleMenu `.ini` file for PICO-8? In my web trawlings I've seen many games in that format rather than just `.p8` and `.png` separately. They'd still run either way, but it would better for using the alias file.

I will test and if it does not cause problems I will add that compound extension. Thanks.

**Comment by neilswann80** [comment]
> > Do you think it's worth also adding extension `.p8.png` to the SimpleMenu `.ini` file for PICO-8? In my web trawlings I've seen many games in that format rather than just `.p8` and `.png` separately. They'd still run either way, but it would better for using the alias file.
> 
> I will test and if it does not cause problems I will add that compound extension. Thanks.

Unfortunately it doesn't look like SimpleMenu supports compound extensions, so users will have to rename their PICO-8 files manually to be either solely `p8` or `png` if they want the alias file to work. Easy enough to do in bulk via the command line. 

If the roms are named `.png` they show the built-in "cart" preview image by default.  They would have to be renamed `.p8` to show scraped images in the `.previews` folder.  

Perhaps this info is worth adding to the wiki?  I'd be happy to make an edit if you like.

**Pull request merged**
